title: Destiny Saga

remote_theme: BlueStar03/theme@v1.0.0

toc-include-h1: true

font_base: 16px
panel_width: 22em
accent_color: blue
content_max: 68em  

nav:
  - title: .ğŸ  Home
    url: /

plugins:
  - jekyll-remote-theme
