title: Destiny Saga

plugins:
  - jekyll-remote-theme

remote_theme: BlueStar03/theme@v3.0.0

toc-include-h1: true

toc_icon: fa fa-list

colors:
  accent:    "#6495ed"   # link/buttons highlight

nav:
  - title: ğŸ  Home
    url: /

plugins:
  - jekyll-remote-theme
